server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          #这是其他项目配置文件的git仓库地址
          uri: https://github.com/liyudi1991/SpringCloudProject.git
          searchPaths: '{application}'
          password: liyudi1991
          username: Dizhi/0511
